# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE = "centos/7"
NODE_COUNT = 3

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}.vagrant" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node-#{i}.vagrant"
      subconfig.vm.network :private_network, ip: "192.168.50.#{i + 9}"
    end
  end
end


