---
- hosts: 192.168.50.10
  gather_facts: no
  vars:
    consul:
      server:
        bind_addr: 192.168.50.10
        datacenter: "SCM-AI-TEAM"
   
  tasks:
    - name: install unzip
      yum:
        name: unzip
      become: yes

    - name: get consul
      get_url: 
        url: https://releases.hashicorp.com/consul/1.0.6/consul_1.0.6_linux_amd64.zip
        dest: /tmp

    - name: create target directory
      file:
        path: /opt/consul
        state: directory
        owner: root
        group: root
        mode: 644
      become: yes
           
    - name: unarchive consul
      unarchive: 
        src: /tmp/consul_1.0.6_linux_amd64.zip
        dest: /opt/consul
        remote_src: yes
      become: yes
       
    - name: remove zipfile
      file: 
        path: /tmp/consul_1.0.6_linux_amd64.zip
        state: absent

    - name: create config directory
      file:
        path: /etc/consul.d
        state: directory
        owner: root
        group: root
        mode: 644
      become: yes

    - name: create data directory
      file:
        path: /var/consul
        state: directory
        owner: root
        group: root
        mode: 644
      become: yes

    - name: deploy sever config file
      template:
        src: server.json.j2
        dest: /etc/consul.d/config.json
        group: root
        owner: root
        mode: 644
      become: yes

    - name: start consul
      shell: "nohup /opt/consul/consul agent -config-file /etc/consul.d/config.json -ui & "
      become: yes



