---
- hosts: 192.168.50.10
  gather_facts: no
  vars:
    consul:
      server:
        bind_addr: 192.168.50.10
        datacenter: "SCM-AI-TEAM"
   
  tasks:

    - name: get nomad
      get_url: 
        url: https://releases.hashicorp.com/nomad/0.7.1/nomad_0.7.1_linux_amd64-lxc.zip
        dest: /tmp

    - name: get epel
      get_url: 
        url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
        dest: /tmp

    - name: install epel
      yum:
        name: /tmp/epel-release-latest-7.noarch.rpm
        state: latest 
      become: yes`

    - name: install lxc-libs
      yum:
        name: lxc-libs-1.0.11-1.el7.x86_64
        state: latest
      become: yes

    - name: create target directory
      file:
        path: /opt/nomad
        state: directory
        owner: root
        group: root
        mode: 644
      become: yes
           
    - name: unarchive consul
      unarchive: 
        src: /tmp/nomad_0.7.1_linux_amd64-lxc.zip
        dest: /opt/consul
        remote_src: yes
      become: yes
       
    - name: remove zipfile
      file: 
        path: /tmp/nomad_0.7.1_linux_amd64-lxc.zip
        state: absent

    - name: start nomad 
      shell: "nohup /opt/nomad/nomad agent -dev & "
      become: yes



