---
- hosts: localhost
  gather_facts: no

- import_playbook: sub_install.consul.agent.yml node_name=node-2.vagrant ip_addr=192.168.50.11
- import_playbook: sub_install.consul.agent.yml node_name=node-3.vagrant ip_addr=192.168.50.12


