---
- hosts: 192.168.50.10
  gather_facts: no
   
  tasks:
    - name: kill existing running instances
      shell: "ps x | grep consul | grep -v grep | awk '{print \"kill -9 \"$1}' | sh"
      become: yes




    - name: start consul
      shell: "nohup /opt/consul/consul agent -config-file /etc/consul.d/config.json -ui & "
      become: yes



